services:
  - type: web
    name: Normalisation
    runtime: node
    repo: https://github.com/OpenPecha/pecha-tool-for-line-image.git
    branch: feat-dictionary
    plan: starter
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: normalisation-pg
          property: connectionString

databases:
  - name: normalisation-pg
    plan: starter
