services:
  - type: web
    name: line-image
    env: node
    plan: standard
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: line-image-pg
          property: connectionString

databases:
  - name: line-image-pg
    plan: standard
